coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 70%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

ignore:
  - "**/*_test.go"
  - "**/mock/**"
  - "cmd/**"
  - "scripts/**"
  - "frontend/**"
  - "docs/**"
  - "assets/**"
  - "migrations/**"
  - "**/*.sql"
  - "internal/storage/s3.go" # S3 storage is production only code. 

