apiVersion: v1
kind: Service
metadata:
  name: bookwish-service
spec:
  selector:
    app: 986129558966.dkr.ecr.ap-northeast-2.amazonaws.com/web-xss-filtering-bypass:latest
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
