apiVersion: v1
kind: Pod
metadata:
  name: simple-note-manager-pod
spec:
  containers:
    - name: simple-note-manager-container
      image: 986129558966.dkr.ecr.ap-northeast-2.amazonaws.com/web-simple-note-manager:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 5000
      resources:
        limits:
          memory: "128Mi"
          cpu: "100m"
        requests:
          memory: "128Mi"
          cpu: "100m"
