apiVersion: v1
kind: Sandbox
metadata:
  name: bookwish-sandbox
spec:
  containers:
    - name: bookwish-container
      image: 986129558966.dkr.ecr.ap-northeast-2.amazonaws.com/web-bookwish:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8000
      resources:
        limits:
          memory: "128Mi"
          cpu: "100m"
        requests:
          memory: "128Mi"
          cpu: "100m" 
