apiVersion: v1
kind: Service
metadata:
  name: bookwish-service
spec:
  selector:
    app: 986129558966.dkr.ecr.ap-northeast-2.amazonaws.com/web-simple-note-manager:latest
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
